spring:
   application: 
      name: spring-eurake-client
 #thymeleaf 就这个返回的静态页面
  # thymeleaf:
   #  suffix: .html
   #  prefix: classpath:/templates/
   mvc:
     view:
       suffix: .jsp
       prefix:  /WEB-INF/jsp/
server:
    port: 8092
#eureka 配置 服务端  
eureka: 
   client: 
       serviceUrl:  
          defaultZone: http://localhost:8091/eureka/
feign:
  hystrix:
    enabled:  true
  client:
     config:
       remote-service:           #服务名，填写default为所有服务
          connectTimeout: 1000
          readTimeout: 12000
#日志的地址
logging:
  file: D:\\logs\\gfzs_smart.log
  level:
    root: info
# actuator  监控可以看到bean   ， health   各个服务的正常情况
endpoints:
  autoconfig:
    sensitive: false
